### ISSUE TITLE
RTL support?

### ISSUE THREAD

**Issue by blai** [inuitcss/objects.media#2]
Sorry that this may not be the right place to start this discussion, but it looks like the `media--rev` was introduced to support RTL use case (or maybe not), but not in a very generic way (as obviously `media` is not the only module that needs RTL support).

I would expect the implementation begins in `inuit-defaults` (or maybe a new module `inuit-rtl`), which should define variables `$left` and `$right`, and be used by all other inuit modules for all directional properties (e.g. `margin-left` would become `margin-#{$left}`, `float: left` would become `float: $left`, etc...).

It'd be very nice if RTL support could be implemented for all core inuit modules.

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
